;this file for FamiTone2 library generated by FamiStudio

retropia_soundtrack_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $b0 ;instrument 00 (Bassish)
	.word @env9, @env0, @env0
	.byte $00
	.byte $f0 ;instrument 01 (Lead)
	.word @env1, @env0, @env0
	.byte $00
	.byte $30 ;instrument 02 (Noise-Bumbo (F#2))
	.word @env7, @env6, @env0
	.byte $00
	.byte $30 ;instrument 03 (Noise-Prato (D#2))
	.word @env3, @env5, @env0
	.byte $00
	.byte $30 ;instrument 04 (Tri-Bumbo)
	.word @env10, @env0, @env4
	.byte $00
	.byte $30 ;instrument 05 (Tri-Caixa)
	.word @env2, @env0, @env8
	.byte $00

@samples:
@env0:
	.byte $c0,$7f,$00,$00
@env1:
	.byte $cf,$10,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$02,$c2,$02,$c1,$04,$c0,$00,$13
@env2:
	.byte $cf,$02,$c0,$00,$02
@env3:
	.byte $c8,$c6,$02,$c0,$00,$03
@env4:
	.byte $c0,$f9,$00,$01
@env5:
	.byte $c0,$c3,$00,$01
@env6:
	.byte $c3,$be,$bf,$00,$02
@env7:
	.byte $cb,$ca,$c8,$c6,$c4,$c2,$c0,$00,$06
@env8:
	.byte $c0,$84,$00,$01
@env9:
	.byte $c1,$c3,$c4,$c5,$c6,$c5,$c6,$c5,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$0f
@env10:
	.byte $cf,$05,$c0,$c0,$c0,$00,$04

@song0ch0:
	.byte $fb, $0c
@song0ch0loop:
@ref0:
	.byte $83,$82,$31,$38,$85,$46,$8d
@ref1:
	.byte $48,$44,$49,$41,$45,$3a,$8b,$00
@ref2:
	.byte $83,$31,$38,$85,$46,$8d
@ref3:
	.byte $46,$85,$39,$3d,$35,$38,$87,$00
@ref4:
	.byte $83,$39,$3d,$4a,$85,$42,$89
@ref5:
	.byte $46,$85,$50,$4c,$46,$3c,$42,$35,$35,$3c,$83
	.byte $ff,$06
	.word @ref2
	.byte $ff,$08
	.word @ref3
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref6:
	.byte $80,$13,$17,$1d,$17,$13,$17,$1d,$16,$81
@ref7:
	.byte $1b,$21,$29,$21,$1b,$21,$29,$20,$81
@ref8:
	.byte $13,$17,$1d,$17,$13,$17,$1d,$16,$81
	.byte $ff,$09
	.word @ref7
	.byte $ff,$09
	.word @ref8
	.byte $ff,$09
	.word @ref7
	.byte $ff,$09
	.word @ref8
	.byte $ff,$09
	.word @ref7
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref9:
	.byte $88,$26,$00,$83,$26,$00,$83,$26,$00,$8a,$2b,$88,$26,$00,$8a,$2a,$81
	.byte $ff,$0d
	.word @ref9
	.byte $ff,$0d
	.word @ref9
	.byte $ff,$0d
	.word @ref9
	.byte $ff,$0d
	.word @ref9
	.byte $ff,$0d
	.word @ref9
	.byte $ff,$0d
	.word @ref9
	.byte $ff,$0d
	.word @ref9
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref10:
	.byte $84,$3d,$86,$38,$38,$84,$3d,$86,$38,$84,$3c,$83,$86,$38,$38,$84,$3d,$86,$38,$81
	.byte $ff,$0c
	.word @ref10
	.byte $ff,$0c
	.word @ref10
	.byte $ff,$0c
	.word @ref10
	.byte $ff,$0c
	.word @ref10
	.byte $ff,$0c
	.word @ref10
	.byte $ff,$0c
	.word @ref10
	.byte $ff,$0c
	.word @ref10
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref11:
	.byte $9f
@ref12:
	.byte $9f
@ref13:
	.byte $9f
@ref14:
	.byte $9f
@ref15:
	.byte $9f
@ref16:
	.byte $9f
@ref17:
	.byte $9f
@ref18:
	.byte $9f
	.byte $fd
	.word @song0ch4loop
